// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOePJgaLa4xkiTCMvMUP_C_YjZKWDGOM',
    appId: '1:951773484453:android:0fb3caf6466fcd058e844c',
    messagingSenderId: '951773484453',
    projectId: 'chattingapp-6fa9b',
    storageBucket: 'chattingapp-6fa9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh61_rE70HIlDm7yTVRXzfOsYTSpc5BME',
    appId: '1:951773484453:ios:a2eceb15aadd39e78e844c',
    messagingSenderId: '951773484453',
    projectId: 'chattingapp-6fa9b',
    storageBucket: 'chattingapp-6fa9b.firebasestorage.app',
    androidClientId: '951773484453-6glfpbhtv64t6shhe73vvjktdq01v4o6.apps.googleusercontent.com',
    iosClientId: '951773484453-246h04hvl2s4to5p7mtik0d6ra1gejvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingapp',
  );

}